/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.jfermat.strava.api;

import io.github.jfermat.strava.model.Fault;
import io.github.jfermat.strava.model.Route;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RoutesApi
 */
@Ignore
public class RoutesApiTest {

    private final RoutesApi api = new RoutesApi();

    /**
     * Export Route GPX
     *
     * Returns a GPX file of the route. Requires read_all scope for private routes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRouteAsGPXTest() {
        Long id = null;
        api.getRouteAsGPX(id);

        // TODO: test validations
    }
    /**
     * Export Route TCX
     *
     * Returns a TCX file of the route. Requires read_all scope for private routes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRouteAsTCXTest() {
        Long id = null;
        api.getRouteAsTCX(id);

        // TODO: test validations
    }
    /**
     * Get Route
     *
     * Returns a route using its identifier. Requires read_all scope for private routes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRouteByIdTest() {
        Long id = null;
        Route response = api.getRouteById(id);

        // TODO: test validations
    }
    /**
     * List Athlete Routes
     *
     * Returns a list of the routes created by the authenticated athlete. Private routes are filtered out unless requested by a token with read_all scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRoutesByAthleteIdTest() {
        Integer page = null;
        Integer perPage = null;
        List<Route> response = api.getRoutesByAthleteId(page, perPage);

        // TODO: test validations
    }
}
