/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.jfermat.strava.api;

import io.github.jfermat.strava.model.ActivityType;
import io.github.jfermat.strava.model.Fault;
import java.io.File;
import io.github.jfermat.strava.model.Upload;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadsApi
 */
@Ignore
public class UploadsApiTest {

    private final UploadsApi api = new UploadsApi();

    /**
     * Upload Activity
     *
     * Uploads a new data file to create an activity from. Requires activity:write scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUploadTest() {
        File file = null;
        ActivityType activityType = null;
        String name = null;
        String description = null;
        String trainer = null;
        String commute = null;
        String dataType = null;
        String externalId = null;
        Upload response = api.createUpload(file, activityType, name, description, trainer, commute, dataType, externalId);

        // TODO: test validations
    }
    /**
     * Get Upload
     *
     * Returns an upload for a given identifier. Requires activity:write scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUploadByIdTest() {
        Long uploadId = null;
        Upload response = api.getUploadById(uploadId);

        // TODO: test validations
    }
}
