/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.jfermat.strava.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.jfermat.strava.model.SummaryGear;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * DetailedGear
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-10T09:15:14.081+01:00[Europe/Paris]")
public class DetailedGear extends SummaryGear {
  @JsonProperty("brand_name")
  private String brandName = null;

  @JsonProperty("model_name")
  private String modelName = null;

  @JsonProperty("frame_type")
  private Integer frameType = null;

  @JsonProperty("description")
  private String description = null;

  public DetailedGear brandName(String brandName) {
    this.brandName = brandName;
    return this;
  }

   /**
   * The gear&#x27;s brand name.
   * @return brandName
  **/
  @Schema(description = "The gear's brand name.")
  public String getBrandName() {
    return brandName;
  }

  public void setBrandName(String brandName) {
    this.brandName = brandName;
  }

  public DetailedGear modelName(String modelName) {
    this.modelName = modelName;
    return this;
  }

   /**
   * The gear&#x27;s model name.
   * @return modelName
  **/
  @Schema(description = "The gear's model name.")
  public String getModelName() {
    return modelName;
  }

  public void setModelName(String modelName) {
    this.modelName = modelName;
  }

  public DetailedGear frameType(Integer frameType) {
    this.frameType = frameType;
    return this;
  }

   /**
   * The gear&#x27;s frame type (bike only).
   * @return frameType
  **/
  @Schema(description = "The gear's frame type (bike only).")
  public Integer getFrameType() {
    return frameType;
  }

  public void setFrameType(Integer frameType) {
    this.frameType = frameType;
  }

  public DetailedGear description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The gear&#x27;s description.
   * @return description
  **/
  @Schema(description = "The gear's description.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedGear detailedGear = (DetailedGear) o;
    return Objects.equals(this.brandName, detailedGear.brandName) &&
        Objects.equals(this.modelName, detailedGear.modelName) &&
        Objects.equals(this.frameType, detailedGear.frameType) &&
        Objects.equals(this.description, detailedGear.description) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(brandName, modelName, frameType, description, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedGear {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    frameType: ").append(toIndentedString(frameType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
