/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.jfermat.strava.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * SummarySegmentEffort
 */


public class SummarySegmentEffort {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("activity_id")
  private Long activityId = null;

  @JsonProperty("elapsed_time")
  private Integer elapsedTime = null;

  @JsonProperty("start_date")
  private OffsetDateTime startDate = null;

  @JsonProperty("start_date_local")
  private OffsetDateTime startDateLocal = null;

  @JsonProperty("distance")
  private Float distance = null;

  @JsonProperty("is_kom")
  private Boolean isKom = null;

  public SummarySegmentEffort id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier of this effort
   * @return id
  **/
  @Schema(description = "The unique identifier of this effort")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SummarySegmentEffort activityId(Long activityId) {
    this.activityId = activityId;
    return this;
  }

   /**
   * The unique identifier of the activity related to this effort
   * @return activityId
  **/
  @Schema(description = "The unique identifier of the activity related to this effort")
  public Long getActivityId() {
    return activityId;
  }

  public void setActivityId(Long activityId) {
    this.activityId = activityId;
  }

  public SummarySegmentEffort elapsedTime(Integer elapsedTime) {
    this.elapsedTime = elapsedTime;
    return this;
  }

   /**
   * The effort&#x27;s elapsed time
   * @return elapsedTime
  **/
  @Schema(description = "The effort's elapsed time")
  public Integer getElapsedTime() {
    return elapsedTime;
  }

  public void setElapsedTime(Integer elapsedTime) {
    this.elapsedTime = elapsedTime;
  }

  public SummarySegmentEffort startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * The time at which the effort was started.
   * @return startDate
  **/
  @Schema(description = "The time at which the effort was started.")
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public SummarySegmentEffort startDateLocal(OffsetDateTime startDateLocal) {
    this.startDateLocal = startDateLocal;
    return this;
  }

   /**
   * The time at which the effort was started in the local timezone.
   * @return startDateLocal
  **/
  @Schema(description = "The time at which the effort was started in the local timezone.")
  public OffsetDateTime getStartDateLocal() {
    return startDateLocal;
  }

  public void setStartDateLocal(OffsetDateTime startDateLocal) {
    this.startDateLocal = startDateLocal;
  }

  public SummarySegmentEffort distance(Float distance) {
    this.distance = distance;
    return this;
  }

   /**
   * The effort&#x27;s distance in meters
   * @return distance
  **/
  @Schema(description = "The effort's distance in meters")
  public Float getDistance() {
    return distance;
  }

  public void setDistance(Float distance) {
    this.distance = distance;
  }

  public SummarySegmentEffort isKom(Boolean isKom) {
    this.isKom = isKom;
    return this;
  }

   /**
   * Whether this effort is the current best on the leaderboard
   * @return isKom
  **/
  @Schema(description = "Whether this effort is the current best on the leaderboard")
  public Boolean isIsKom() {
    return isKom;
  }

  public void setIsKom(Boolean isKom) {
    this.isKom = isKom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummarySegmentEffort summarySegmentEffort = (SummarySegmentEffort) o;
    return Objects.equals(this.id, summarySegmentEffort.id) &&
        Objects.equals(this.activityId, summarySegmentEffort.activityId) &&
        Objects.equals(this.elapsedTime, summarySegmentEffort.elapsedTime) &&
        Objects.equals(this.startDate, summarySegmentEffort.startDate) &&
        Objects.equals(this.startDateLocal, summarySegmentEffort.startDateLocal) &&
        Objects.equals(this.distance, summarySegmentEffort.distance) &&
        Objects.equals(this.isKom, summarySegmentEffort.isKom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, activityId, elapsedTime, startDate, startDateLocal, distance, isKom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummarySegmentEffort {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    elapsedTime: ").append(toIndentedString(elapsedTime)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    startDateLocal: ").append(toIndentedString(startDateLocal)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    isKom: ").append(toIndentedString(isKom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
